Add 4 functions related to the app APIs: get/postDeploy & get/putCustomize
kintone/kintoneUtility pull request #14
Opened 2018-03-30 12:17 UTC by shuuji3

Hello, I added 4 functions related to the app APIs:
- `kintoneUtility.rest.postDeploy()`
- `kintoneUtility.rest.getDeploy()`
- `kintoneUtility.rest.getCustomize()`
- `kintoneUtility.rest.putCustomize()`

The docs according to its function are here (in Japanese):
- [アプリの設定の運用環境への反映 – cybozu developer network](https://developer.cybozu.io/hc/ja/articles/204699420)
- [アプリの設定の運用環境への反映状況確認 – cybozu developer network](https://developer.cybozu.io/hc/ja/articles/210100886)
- [JavaScript / CSSカスタマイズ設定の取得 – cybozu developer network](https://developer.cybozu.io/hc/ja/articles/204529824)
- [JavaScript / CSSカスタマイズ設定の変更 – cybozu developer network](https://developer.cybozu.io/hc/ja/articles/204529834)

Feel free to tell me any comment if you have! 😃

2018-04-03 02:54 UTC, sada-nishio commented
@shuuji3 
Thank you for your pull request.
We'll make sure it.

2018-04-03 04:10 UTC, shuuji3 commented
Thanks, I'm looking forward to your review!

2018-04-04 03:30 UTC, hokimcuc0202 commented on src/js/main.js
> +        postDeploy,
I think the function name should be more clear
+ postDeploy => postDeployAppSettings

2018-04-04 03:30 UTC, hokimcuc0202 commented on src/js/main.js
> +        getDeploy,
I think the function name should be more clear
+ getDeploy => getDeployAppSettings

2018-04-04 03:31 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +* [kintoneUtility.rest.postDeploy](#postDeploy)
I think the function name should be more clear
+ postDeploy => postDeployAppSettings

2018-04-04 03:31 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +* [kintoneUtility.rest.getDeploy](#getDeploy)
I think the function name should be more clear
+ getDeploy => getDeployAppSettings

2018-04-04 03:31 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +## <a name="postDeploy"> kintoneUtility.rest.postDeploy(param)
I think the function name should be more clear
+ postDeploy => postDeployAppSettings

2018-04-04 03:31 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +kintoneUtility.rest.postDeploy({
I think the function name should be more clear
+ postDeploy => postDeployAppSettings

2018-04-04 03:31 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +## <a name="getDeploy"> kintoneUtility.rest.getDeploy(param)
I think the function name should be more clear
+ getDeploy => getDeployAppSettings

2018-04-04 03:32 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +kintoneUtility.rest.getDeploy({
I think the function name should be more clear
+ getDeploy => getDeployAppSettings

2018-04-04 03:33 UTC, hokimcuc0202 commented on src/js/rest/getDeploy.js
> +import createError from './common/createError';
I think the file name should be more clear
+ getDeploy => getDeployAppSettings

2018-04-04 03:33 UTC, hokimcuc0202 commented on src/js/rest/postDeploy.js
> +import createError from './common/createError';
I think the file name should be more clear
+ postDeploy => postDeployAppSettings

2018-04-04 04:17 UTC, hokimcuc0202 requested changes
@shuuji3 
I have some feedback for your implementing.
Please help me check it.

2018-04-04 04:17 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +* [kintoneUtility.rest.getDeploy](#getDeploy)
I think the function name should be more clear
+ postDeploy => postDeployAppSettings
+ getDeploy => getDeployStatus

2018-04-04 04:17 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +## <a name="postDeploy"> kintoneUtility.rest.postDeploy(param)
I think the function name should be more clear
+ postDeploy => postDeployAppSettings

2018-04-04 04:17 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +## <a name="getDeploy"> kintoneUtility.rest.getDeploy(param)
I think the function name should be more clear
+ getDeploy => getDeployStatus

2018-04-04 04:17 UTC, hokimcuc0202 commented on src/js/main.js
> +import postDeploy from './rest/postDeploy';
I think the function name should be more clear
+ postDeploy => postDeployAppSettings

2018-04-04 04:17 UTC, hokimcuc0202 commented on src/js/main.js
> +import getDeploy from './rest/getDeploy';
I think the function name should be more clear
+ getDeploy => getDeployStatus

2018-04-04 04:17 UTC, hokimcuc0202 commented on src/js/main.js
> +        postDeploy,
I think the function name should be more clear
+ postDeploy => postDeployAppSettings

2018-04-04 04:17 UTC, hokimcuc0202 commented on src/js/main.js
> +        getDeploy,
I think the function name should be more clear
+ getDeploy => getDeployStatus

2018-04-04 04:17 UTC, hokimcuc0202 commented on src/js/rest/getDeploy.js
> +import createError from './common/createError';
I think the file name should be more clear
+ getDeploy => getDeployStatus

2018-04-04 04:17 UTC, hokimcuc0202 commented on src/js/rest/postDeploy.js
> +import createError from './common/createError';
I think the file name should be more clear
+ postDeploy => postDeployAppSettings

2018-04-04 10:48 UTC, shuuji3 commented
That's reasonable. I've changed the names.

2018-04-05 04:18 UTC, hokimcuc0202 requested changes
@shuuji3 
Sorry for bothering you many times.
I have added some missing feedback.
I am very sorry for the review missing  :((.

2018-04-05 04:18 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +* [kintoneUtility.rest.getCustomize](#getCustomize)
Because customize is a verb, so the function name should be changed
getCustomize => getCustomization
putCustomize => updateCustomization

2018-04-05 04:18 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +* Get the information of JavaScrit/CSS files used to customize an app.
Because customize is a verb, so the function name should be changed
getCustomize => getCustomization

2018-04-05 04:18 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +## <a name="putCustomize"> kintoneUtility.rest.putCustomize(param)
Because customize is a verb, so the function name should be changed
putCustomize => updateCustomization

2018-04-05 04:18 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +kintoneUtility.rest.putCustomize({
Because customize is a verb, so the function name should be changed
putCustomize => updateCustomization

2018-04-05 04:18 UTC, hokimcuc0202 commented on guides/rest_doc.md
> +kintoneUtility.rest.getCustomize({
Because customize is a verb, so the function name should be changed
getCustomize => getCustomization

2018-04-05 04:18 UTC, hokimcuc0202 commented on src/js/main.js
> +import putCustomize from './rest/putCustomize';
Because customize is a verb, so the function name should be changed
getCustomize => getCustomization
putCustomize => updateCustomization

2018-04-05 04:18 UTC, hokimcuc0202 commented on src/js/main.js
> +        putCustomize,
Because customize is a verb, so the function name should be changed
getCustomize => getCustomization
putCustomize => updateCustomization

2018-04-05 04:18 UTC, hokimcuc0202 commented on src/js/rest/getCustomize.js
> +import createError from './common/createError';
Because customize is a verb, so the file name should be changed
getCustomize => getCustomization

2018-04-05 04:18 UTC, hokimcuc0202 commented on src/js/rest/putCustomize.js
> +import createError from './common/createError';
Because customize is a verb, so the function name should be changed
putCustomize => updateCustomization

2018-04-05 16:26 UTC, shuuji3 commented
No problem!😊 I've fixed the names you pointed out too.

2018-04-06 02:18 UTC, hokimcuc0202 commented
@shuuji3 
The function name is ok.
We will check functions operation.

2018-04-06 03:58 UTC, hokimcuc0202 approved these changes

2018-04-26 10:47 UTC, vutranshield commented on src/js/rest/postDeploy.js
> + *  @param {number?} params.revision
Because revision comes with a particular app, so I think this line of code should be changed to something like params.apps[].revision

2018-04-26 10:52 UTC, vutranshield commented on src/js/rest/getDeploy.js
> +import createError from './common/createError';
Perhaps the name "getAppDeployStatus" is better in this case
https://developer.kintone.io/hc/en-us/articles/115004890947

2018-04-26 15:22 UTC, shuuji3 commented on src/js/rest/postDeploy.js
> + *  @param {number?} params.revision
Thanks for pointing out. It's my mistake.

2018-04-26 15:24 UTC, shuuji3 commented on src/js/rest/getDeploy.js
> +import createError from './common/createError';
I agree the name is more readable and fit the document. I'll change the name.

2018-04-27 09:35 UTC, vutranshield commented on guides/rest_doc.md
> +* Update the information of JavaScrit/CSS files used to customize an app.
Please be noticed that a typo mistake has taken in this description. I recommend to change to "Updates the JavaScript and CSS Customization settings of an App." for fitting API's description

2018-04-27 09:35 UTC, vutranshield commented on guides/rest_doc.md
> +* Get the information of JavaScrit/CSS files used to customize an app.
Please be noticed that a typo mistake has taken in this description. I recommend to change to "Gets the JavaScript and CSS Customization settings of an App." for fitting API's description.

2018-04-27 10:15 UTC, vutranshield commented on guides/rest_doc.md
> +* [kintoneUtility.rest.getDeployStatus](#getDeployStatus)
Function name and link anchor need to be updated

2018-04-27 23:09 UTC, shuuji3 commented
Thank you for your review. I've updated the documentation.

2018-05-07 08:04 UTC, merged